"""initial schema

Revision ID: 50c7163ce934
Revises: 638e8e9a05d1
Create Date: 2026-02-11 09:56:42.454981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c7163ce934'
down_revision: Union[str, Sequence[str], None] = '638e8e9a05d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=True),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.Column('niveau', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_utilisateur_id'), 'utilisateur', ['id'], unique=False)
    op.create_table('historique_api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('donnees_requete', sa.Text(), nullable=True),
    sa.Column('statut_reponse', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcours_apprentissage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=True),
    sa.Column('contenu_genere_ia', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantation_arbres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_arbres', sa.Integer(), nullable=True),
    sa.Column('fournisseur_api', sa.String(length=100), nullable=True),
    sa.Column('date_plantation', sa.DateTime(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_connexion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('ip_adresse', sa.String(length=50), nullable=True),
    sa.Column('appareil', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcours_cours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('parcours_id', sa.Integer(), nullable=True),
    sa.Column('cours_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcours_id'], ['parcours_apprentissage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_apprentissage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debut', sa.DateTime(), nullable=True),
    sa.Column('fin', sa.DateTime(), nullable=True),
    sa.Column('duree_minutes', sa.Integer(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('parcours_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parcours_id'], ['parcours_apprentissage.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empreinte_carbone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('co2_grammes', sa.Float(), nullable=True),
    sa.Column('energie_kwh', sa.Float(), nullable=True),
    sa.Column('equivalent_arbres', sa.Float(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session_apprentissage.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('reponse_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('reponse', sa.Text(), nullable=True),
    sa.Column('modele', sa.String(length=100), nullable=True),
    sa.Column('tokens_utilises', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session_apprentissage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reponse_ia')
    op.drop_table('empreinte_carbone')
    op.drop_table('session_apprentissage')
    op.drop_table('parcours_cours')
    op.drop_table('session_connexion')
    op.drop_table('plantation_arbres')
    op.drop_table('parcours_apprentissage')
    op.drop_table('historique_api')
    op.drop_index(op.f('ix_utilisateur_id'), table_name='utilisateur')
    op.drop_table('utilisateur')
    op.drop_table('cours')
    # ### end Alembic commands ###
